name: "Documentation"
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ferdnyc/sphinx-action@controlled-apt
        with:
          install: git
          pre-build-command: "pip install .[docs]"
          docs-folder: "docs/"
          container: sphinx4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/dev'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
